from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt # Import the Bcrypt module
from flask_login import LoginManager

app = Flask(__name__)
# Create an autogenerated Secret key in order to protect our app 
# against modyfying cookies, cross-site requests or forgert attacks
app.config['SECRET_KEY'] = '07592e246b2e9c6e5ac627d9b044e850'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///courses.db'
db = SQLAlchemy(app)

# Initialize the Bcrypt object so we can hash the passwords
bcrypt = Bcrypt(app)

# Initialize the login manager to handle of the sessions in the background for us. 
login_manager = LoginManager(app)

# Require from user to login to see some of the pages.
login_manager.login_view = 'login'
login_manager.login_message_category = 'info'


from courses import routes

'''
    Random Students
    ================
    Email: vangelis@gmail.com
    Password: pass1
    -----
    Email: kostas@gmail.com
    Password: pass4
    -----
    Email: stella@gmail.com
    Password: pass8

    Random Professors
    ==================
    Email: georgiou@gmail.com
    Password: pass2
    -----
    Email: sotiriou@gmail.com
    Password: pass5
    -----
    Email: dimitriou@gmail.com
    Password: pass7 


'''
